import { Header } from '@/components/feature/Header';
import './globals.css';
import { Footer } from '@/components/feature/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="text-white">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
