name: Release
on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{  github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: actions/checkout@v3

      - name: Use PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Create release
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore(release): version packages'
          title: 'chore(release): version packages'
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
